### ISSUE TITLE
Unable to change the settings anymore. This never used to be an issue.

### ISSUE THREAD

**Issue by script01** [killburne/custom-duelingbook#8] opened 2023-05-22 17:10 UTC
The Cog to change settings does not appear for me. I have tried on two different browsers (Brave, Firefox)
Now I don't know what has changed, because last time i had a working computer (roughly a month ago) the cog would appear at the bottom left. However it does not seem to the the case anymore. Thanks for the help it is greatly appreciated.
![Cog](https://github.com/killburne/custom-duelingbook/assets/134315543/0a288b58-3bde-478b-837c-7fbb1cdf3e95)

**Comment by amadejkastelic** [comment] 2023-05-23 17:38
Seems like this is caused by the GM_config upgrade: https://github.com/sizzlemctwizzle/GM_config/issues/113. I'll try to fix this today and open a PR.

**Comment by killburne** [comment] 2023-05-23 19:24
should be fixed now thanks to @amadejkastelic

**Closed by killburne** 2023-05-23 19:24 UTC
